services:
  ml-lab:
    build: .
    container_name: diabetes_s5e12_env
    volumes:
      - .:/app
      - ./.sercrets/kaggle.json:/root/.kaggle/kaggle.json
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilites: [gpu]
    
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotenookApp.token=''
    retsart: unless-stopped
  