services:
  ml-lab:
    build: .
    container_name: diabetes_s5e12_env
    volumes:
      - .:/app
    ports:
      - "8888:8888" #jupyter
      - "8501:8501" #streamlit
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotenookApp.token=''
    restart: unless-stopped
  